"""Added new columns to Users and TodoItem

Revision ID: 5ec72ebc04eb
Revises: 
Create Date: 2024-12-17 12:40:11.983399

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5ec72ebc04eb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(80), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=900),
            existing_nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
            existing_type=sa.String(length=900),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


    # ### end Alembic commands ###
