"""Add data_completed column

Revision ID: 973c9ebbe742
Revises: 
Create Date: 2024-12-07 15:05:17.243161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973c9ebbe742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_completed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.drop_column('data_completed')

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_pkey')
    )
    # ### end Alembic commands ###
